### ISSUE TITLE
Crossplatform GL functions loader

### ISSUE THREAD

**Issue by alexey-lysiuk** [Panzerschrek/panzer_ogl_lib#1]
I would like to ask about possibility to replace custom OpenGL functions loader with existing crossplatform library, like [GLEW](http://glew.sourceforge.net/), or pre-generated loader, like [glLoadGen](https://bitbucket.org/alfonse/glloadgen/wiki/Home).

While the first one introduces a new dependency, which you probably wanted to avoid, the second creates header and source files with required definitions only.
Personally I prefer the second approach and it's quite close to what you created by hand.

The reason of my question is inability to compile PanzerChasm with Visual Studio and Xcode out of the box because of this functions loader. And fixing it is doable but not so trivial.

**Comment by Panzerschrek** [comment]
I do not see any problems in current GL functions loader. It works on Windows and GNU/Linux.
If you have any specific problems with it on Visual Studio or XCode, show here build log.

**Comment by alexey-lysiuk** [comment]
Here is the beginning of the log from Visual Studio 2015 with the default toolchain:
```
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1157): error C2144: syntax error: 'void' should be preceded by ';'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1157): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1157): error C2182: 'APIENTRY': illegal use of type 'void'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1157): error C2146: syntax error: missing ';' before identifier 'glAccum'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1158): error C2144: syntax error: 'void' should be preceded by ';'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1158): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1158): error C2086: 'int WINGDIAPI': redefinition
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1157): note: see declaration of 'WINGDIAPI'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1158): error C2182: 'APIENTRY': illegal use of type 'void'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1158): error C2086: 'int APIENTRY': redefinition
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1157): note: see declaration of 'APIENTRY'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1158): error C2146: syntax error: missing ';' before identifier 'glAlphaFunc'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1159): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1159): error C2086: 'int WINGDIAPI': redefinition
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1157): note: see declaration of 'WINGDIAPI'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1159): error C2146: syntax error: missing ';' before identifier 'GLboolean'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1160): error C2144: syntax error: 'void' should be preceded by ';'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1160): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\GL/gl.h(1160): error C2086: 'int WINGDIAPI': redefinition
```
Unlike the case with Xcode this is quite easy to fix. I added the following lines
```
#ifdef _MSC_VER
#define NOMINMAX
#include <windows.h>
#endif // _MSC_VER
```
before
```
#include <GL/gl.h>
```
to `panzer_ogl_lib.hpp` file.

I didn't save logs from Xcode but apparently it required more changes to be able to compile it. With exception of already pushed effects sprites sorting it runs fine on macOS.
Probably I will experiment a bit more with it later to find the smallest possible fix.

**Comment by alexey-lysiuk** [comment]
Xcode build logs are [here](https://gist.github.com/alexey-lysiuk/69263867da8e0b0eda9646e3dc3fddd3). As you can see almost all issues are caused by GL functions loader.

There is no `GL/gl.h` header on Apple's platform.
There is OpenGL framework which can used by including `OpenGL/OpenGL.h` like I did to make the first log.
However inside the framework there is `OpenGL/gl.h` but using it produces lots of errors too, the second log.

Found a cool comment in `glcorearb.h`
```
 * It is not possible to #include both <GL/glcorearb.h> and either of
 * <GL/gl.h> or <GL/glext.h> in the same source file.
```
